---
Title: Housing Introduction
output: html_document
---

# Introduction to Housing Affordability  

---

The dataset that we used for this part of the project is from the [National Low Income Housing Coalition](https://nlihc.org/oor). It provides information on monthly rent that is required in order to afford the selected numbers of bedrooms by county level.  

---

## Area of Interest


#### Affordability Throughout Washington

Data is based on county level housing affordability from 2011 through 2016.

#### Specific County Affordability progression 

Specific County progression trend from 2011 through 2016. 

---

## Interactions

#### Data Table
Users are able to select their desired number of bedrooms they would like to rent and the year they want to see. The bar graph will showcase the average monthly rent of Washington counties depending on the number of rooms selected.

---

#### Graph Table  
Users are able to select one county and see the rent trends from 2012-2016 in order to predict and budget out for rent if they are interested in moving to the specific area.
